# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: client.proto for package 'client'

require 'grpc'
require 'client_pb'

module Client
  module Greeter
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'client.Greeter'

      rpc :SayHello, ::Client::HelloRequest, ::Client::HelloReply
    end

    Stub = Service.rpc_stub_class
  end
end
