# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test/protos/client.proto

require 'google/protobuf'


descriptor_data = "\n\x18test/protos/client.proto\x12\x06\x63lient\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2A\n\x07Greeter\x12\x36\n\x08SayHello\x12\x14.client.HelloRequest\x1a\x12.client.HelloReply\"\x00\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Client
  HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("client.HelloRequest").msgclass
  HelloReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("client.HelloReply").msgclass
end
