# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test/protos/enum_description_option.proto

require 'google/protobuf'

require 'google/protobuf/descriptor_pb'


descriptor_data = "\n)test/protos/enum_description_option.proto\x12\x0fgrpc_reflection\x1a google/protobuf/descriptor.proto:=\n\x10\x65num_description\x12!.google.protobuf.EnumValueOptions\x18\xd2\x86\x03 \x01(\tb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module GrpcReflection
end
