# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test/protos/nopkg.proto

require 'google/protobuf'


descriptor_data = "\n\x17test/protos/nopkg.proto\"\x1b\n\x0bPingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\tPingReply\x12\x0f\n\x07message\x18\x01 \x01(\t2+\n\x05NoPkg\x12\"\n\x04Ping\x12\x0c.PingRequest\x1a\n.PingReply\"\x00\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

PingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PingRequest").msgclass
PingReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PingReply").msgclass
