# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: test/protos/nopkg.proto for package ''

require 'grpc'
require 'test/protos/nopkg_pb'

module NoPkg
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'NoPkg'

    rpc :Ping, ::PingRequest, ::PingReply
  end

  Stub = Service.rpc_stub_class
end
