# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: test/protos/service.proto for package 'service_test_protos'

require 'grpc'
require 'test/protos/service_pb'

module ServiceTestProtos
  module TestService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'service_test_protos.TestService'

      rpc :UnaryOne, ::ServiceTestProtos::UnaryRequestType, ::ServiceTestProtos::UnaryResponseType
      rpc :UnaryTwo, ::ServiceTestProtos::UnaryRequestType, ::ServiceTestProtos::UnaryResponseType
      rpc :IdempotentMethod, ::ServiceTestProtos::UnaryRequestType, ::ServiceTestProtos::UnaryResponseType
      rpc :PureMethod, ::ServiceTestProtos::UnaryRequestType, ::ServiceTestProtos::UnaryResponseType
      rpc :StreamingMethod, stream(::ServiceTestProtos::StreamRequestType), stream(::ServiceTestProtos::StreamResponseType)
    end

    Stub = Service.rpc_stub_class
  end
end
