# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

require 'google/protobuf'

require 'google/protobuf/descriptor_pb'


descriptor_data = "\n\rservice.proto\x12\x13service_test_protos\x1a google/protobuf/descriptor.proto\" \n\x10UnaryRequestType\x12\x0c\n\x04ping\x18\x01 \x01(\t\"!\n\x11UnaryResponseType\x12\x0c\n\x04pong\x18\x01 \x01(\t\"3\n\x11StreamRequestType\x12\x0c\n\x04ping\x18\x01 \x01(\t\x12\x10\n\x08sequence\x18\x02 \x01(\r\"4\n\x12StreamResponseType\x12\x0c\n\x04pong\x18\x01 \x01(\t\x12\x10\n\x08sequence\x18\x02 \x01(\r\"+\n\x0fTestOptionsType\x12\x18\n\x10int_option_value\x18\x01 \x01(\r2\xfe\x03\n\x0bTestService\x12Y\n\x08UnaryOne\x12%.service_test_protos.UnaryRequestType\x1a&.service_test_protos.UnaryResponseType\x12Y\n\x08UnaryTwo\x12%.service_test_protos.UnaryRequestType\x1a&.service_test_protos.UnaryResponseType\x12\x66\n\x10IdempotentMethod\x12%.service_test_protos.UnaryRequestType\x1a&.service_test_protos.UnaryResponseType\"\x03\x90\x02\x02\x12`\n\nPureMethod\x12%.service_test_protos.UnaryRequestType\x1a&.service_test_protos.UnaryResponseType\"\x03\x90\x02\x01\x12\x66\n\x0fStreamingMethod\x12&.service_test_protos.StreamRequestType\x1a\'.service_test_protos.StreamResponseType(\x01\x30\x01\x1a\x07\x82\xb5\x18\x03\x08\x85\x41\x32\x18\n\x11\x44\x65precatedService\x1a\x03\x88\x02\x01:`\n\x0ctest_options\x12\x1f.google.protobuf.ServiceOptions\x18\xd0\x86\x03 \x01(\x0b\x32$.service_test_protos.TestOptionsType\x88\x01\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module ServiceTestProtos
  UnaryRequestType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("service_test_protos.UnaryRequestType").msgclass
  UnaryResponseType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("service_test_protos.UnaryResponseType").msgclass
  StreamRequestType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("service_test_protos.StreamRequestType").msgclass
  StreamResponseType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("service_test_protos.StreamResponseType").msgclass
  TestOptionsType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("service_test_protos.TestOptionsType").msgclass
end
