# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: test/protos/utilify.proto for package 'utility'

require 'grpc'
require 'test/protos/utilify_pb'

module Utility
  module Clock
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'utility.Clock'

      rpc :Now, ::Utility::ClockRequest, ::Utility::ClockReply
    end

    Stub = Service.rpc_stub_class
  end
end
